"""GYMIO Exercise Catalog — 484 exercises across 15 muscle groups."""

EXERCISES = [
    # === ABS ===
    {"name": "Ab Rollout", "muscle_group": "Abs", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Ab Wheel Rollout", "muscle_group": "Abs", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Band Anti-Rotation Press", "muscle_group": "Abs", "equipment": "Resistance Band", "pattern": "Rotation"},
    {"name": "Barbell Press Sit-Up", "muscle_group": "Abs", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Cable Crunch", "muscle_group": "Abs", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Crunch (Kneeling)", "muscle_group": "Abs", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Crunch (Standing)", "muscle_group": "Abs", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Pallof Press", "muscle_group": "Abs", "equipment": "Cable", "pattern": "Rotation"},
    {"name": "Cable Woodchop", "muscle_group": "Abs", "equipment": "Cable", "pattern": "Rotation"},
    {"name": "Crunch", "muscle_group": "Abs", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Dead Bug", "muscle_group": "Abs", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Decline Sit Up", "muscle_group": "Abs", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Decline Sit-Up", "muscle_group": "Abs", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Dragon Flag", "muscle_group": "Abs", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Hanging Knee Raise", "muscle_group": "Abs", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Hanging Leg Raise", "muscle_group": "Abs", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Hanging Windshield Wiper", "muscle_group": "Abs", "equipment": "Bodyweight", "pattern": "Rotation"},
    {"name": "Hollow Body Hold", "muscle_group": "Abs", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "L-Sit", "muscle_group": "Abs", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Landmine Rotation", "muscle_group": "Abs", "equipment": "Landmine", "pattern": "Rotation"},
    {"name": "Plank", "muscle_group": "Abs", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Resistance Band Pallof Press", "muscle_group": "Abs", "equipment": "Resistance Band", "pattern": "Isolation"},
    {"name": "Reverse Crunch", "muscle_group": "Abs", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Russian Twist", "muscle_group": "Abs", "equipment": "Dumbbell", "pattern": "Rotation"},
    {"name": "Side Plank", "muscle_group": "Abs", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Sit-Up", "muscle_group": "Abs", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Suitcase Carry", "muscle_group": "Abs", "equipment": "Dumbbell", "pattern": "Carry"},
    {"name": "Toes to Bar", "muscle_group": "Abs", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Toes-to-Bar", "muscle_group": "Abs", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "V-Up", "muscle_group": "Abs", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Vertical Leg Raise (Parallel Bars)", "muscle_group": "Abs", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Weighted Crunch", "muscle_group": "Abs", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Weighted Plank", "muscle_group": "Abs", "equipment": "Barbell", "pattern": "Isolation"},
    # === BACK ===
    {"name": "Back Extension", "muscle_group": "Back", "equipment": "Bodyweight", "pattern": "Hinge"},
    {"name": "Band Lat Pulldown", "muscle_group": "Back", "equipment": "Resistance Band", "pattern": "Pull"},
    {"name": "Band Pull Apart", "muscle_group": "Back", "equipment": "Resistance Band", "pattern": "Pull"},
    {"name": "Barbell Bent-Over Row", "muscle_group": "Back", "equipment": "Barbell", "pattern": "Pull"},
    {"name": "Barbell Good Morning", "muscle_group": "Back", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Barbell Pendlay Row", "muscle_group": "Back", "equipment": "Barbell", "pattern": "Pull"},
    {"name": "Barbell Reverse Grip Row", "muscle_group": "Back", "equipment": "Barbell", "pattern": "Pull"},
    {"name": "Barbell Row", "muscle_group": "Back", "equipment": "Barbell", "pattern": "Pull"},
    {"name": "Barbell Seal Row", "muscle_group": "Back", "equipment": "Barbell", "pattern": "Pull"},
    {"name": "Cable Close-Grip Seated Row", "muscle_group": "Back", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Cable One-Arm Row", "muscle_group": "Back", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Cable Pullover", "muscle_group": "Back", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Reverse Grip Seated Row", "muscle_group": "Back", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Cable Rope Seated Row", "muscle_group": "Back", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Cable Row (Seated)", "muscle_group": "Back", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Cable Row (Standing)", "muscle_group": "Back", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Cable Seated Row", "muscle_group": "Back", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Cable Straight-Arm Pulldown", "muscle_group": "Back", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Cable Wide-Grip Seated Row", "muscle_group": "Back", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Chest Supported Row", "muscle_group": "Back", "equipment": "Dumbbell", "pattern": "Pull"},
    {"name": "Chest-Supported Dumbbell Row", "muscle_group": "Back", "equipment": "Dumbbell", "pattern": "Pull"},
    {"name": "Chin Up", "muscle_group": "Back", "equipment": "Bodyweight", "pattern": "Pull"},
    {"name": "Close Grip Lat Pulldown", "muscle_group": "Back", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Dumbbell Incline Row", "muscle_group": "Back", "equipment": "Dumbbell", "pattern": "Pull"},
    {"name": "Dumbbell Pullover", "muscle_group": "Back", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Row", "muscle_group": "Back", "equipment": "Dumbbell", "pattern": "Pull"},
    {"name": "Gorilla Row", "muscle_group": "Back", "equipment": "Dumbbell", "pattern": "Pull"},
    {"name": "Incline Dumbbell Row", "muscle_group": "Back", "equipment": "Dumbbell", "pattern": "Pull"},
    {"name": "Inverted Row", "muscle_group": "Back", "equipment": "Bodyweight", "pattern": "Pull"},
    {"name": "Kettlebell Renegade Row", "muscle_group": "Back", "equipment": "Kettlebell", "pattern": "Pull"},
    {"name": "Kettlebell Row", "muscle_group": "Back", "equipment": "Kettlebell", "pattern": "Pull"},
    {"name": "Kroc Row", "muscle_group": "Back", "equipment": "Dumbbell", "pattern": "Pull"},
    {"name": "Landmine Meadows Row", "muscle_group": "Back", "equipment": "Landmine", "pattern": "Pull"},
    {"name": "Landmine One-Arm Row", "muscle_group": "Back", "equipment": "Landmine", "pattern": "Pull"},
    {"name": "Landmine Row", "muscle_group": "Back", "equipment": "Landmine", "pattern": "Pull"},
    {"name": "Lat Pulldown", "muscle_group": "Back", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Meadows Row", "muscle_group": "Back", "equipment": "Landmine", "pattern": "Pull"},
    {"name": "Neutral Grip Pull Up", "muscle_group": "Back", "equipment": "Bodyweight", "pattern": "Pull"},
    {"name": "Pendlay Row", "muscle_group": "Back", "equipment": "Barbell", "pattern": "Pull"},
    {"name": "Pull Up", "muscle_group": "Back", "equipment": "Bodyweight", "pattern": "Pull"},
    {"name": "Renegade Row", "muscle_group": "Back", "equipment": "Dumbbell", "pattern": "Pull"},
    {"name": "Resistance Band Face Pull", "muscle_group": "Back", "equipment": "Resistance Band", "pattern": "Pull"},
    {"name": "Resistance Band Row", "muscle_group": "Back", "equipment": "Resistance Band", "pattern": "Pull"},
    {"name": "Reverse Grip Lat Pulldown", "muscle_group": "Back", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Seal Row", "muscle_group": "Back", "equipment": "Barbell", "pattern": "Pull"},
    {"name": "Single Arm Cable Row", "muscle_group": "Back", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Single Arm Lat Pulldown", "muscle_group": "Back", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Smith Machine Bent-Over Row", "muscle_group": "Back", "equipment": "Smith Machine", "pattern": "Pull"},
    {"name": "Straight Arm Pulldown", "muscle_group": "Back", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "T-Bar Row", "muscle_group": "Back", "equipment": "Landmine", "pattern": "Pull"},
    {"name": "Trap Bar Bent-Over Row", "muscle_group": "Back", "equipment": "Trap Bar", "pattern": "Pull"},
    {"name": "Weighted Pull Up", "muscle_group": "Back", "equipment": "Bodyweight", "pattern": "Pull"},
    {"name": "Wide Grip Cable Row", "muscle_group": "Back", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Wide Grip Lat Pulldown", "muscle_group": "Back", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Wide Grip Pull Up", "muscle_group": "Back", "equipment": "Bodyweight", "pattern": "Pull"},
    # === BICEPS ===
    {"name": "21s Curl", "muscle_group": "Biceps", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Band Curl", "muscle_group": "Biceps", "equipment": "Resistance Band", "pattern": "Isolation"},
    {"name": "Barbell Curl", "muscle_group": "Biceps", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Barbell Drag Curl", "muscle_group": "Biceps", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Barbell Preacher Curl", "muscle_group": "Biceps", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Barbell Reverse Curl", "muscle_group": "Biceps", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Barbell Spider Curl", "muscle_group": "Biceps", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Bayesian Cable Curl", "muscle_group": "Biceps", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Bodyweight Curl (Inverted)", "muscle_group": "Biceps", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Cable Bayesian Curl", "muscle_group": "Biceps", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Crossover Bicep Curl", "muscle_group": "Biceps", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Curl", "muscle_group": "Biceps", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Curl (Bar)", "muscle_group": "Biceps", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Curl (Rope)", "muscle_group": "Biceps", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Hammer Curl", "muscle_group": "Biceps", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Overhead Curl", "muscle_group": "Biceps", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Concentration Curl", "muscle_group": "Biceps", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Cross Body Curl", "muscle_group": "Biceps", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Drag Curl", "muscle_group": "Biceps", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Dumbbell Concentration Curl", "muscle_group": "Biceps", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Curl", "muscle_group": "Biceps", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Hammer Curl", "muscle_group": "Biceps", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Incline Curl", "muscle_group": "Biceps", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Preacher Curl", "muscle_group": "Biceps", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Reverse Curl", "muscle_group": "Biceps", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Zottman Curl", "muscle_group": "Biceps", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "EZ Bar Curl", "muscle_group": "Biceps", "equipment": "EZ Bar", "pattern": "Isolation"},
    {"name": "EZ Bar Preacher Curl", "muscle_group": "Biceps", "equipment": "EZ Bar", "pattern": "Isolation"},
    {"name": "EZ Bar Reverse Curl", "muscle_group": "Biceps", "equipment": "EZ Bar", "pattern": "Isolation"},
    {"name": "Hammer Curl", "muscle_group": "Biceps", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Incline Dumbbell Curl", "muscle_group": "Biceps", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Kettlebell Curl", "muscle_group": "Biceps", "equipment": "Kettlebell", "pattern": "Isolation"},
    {"name": "Machine Bicep Curl", "muscle_group": "Biceps", "equipment": "Machine", "pattern": "Isolation"},
    {"name": "Preacher Curl", "muscle_group": "Biceps", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Resistance Band Curl", "muscle_group": "Biceps", "equipment": "Resistance Band", "pattern": "Isolation"},
    {"name": "Reverse Curl", "muscle_group": "Biceps", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Spider Curl", "muscle_group": "Biceps", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Zottman Curl", "muscle_group": "Biceps", "equipment": "Dumbbell", "pattern": "Isolation"},
    # === CALVES ===
    {"name": "Barbell Seated Calf Raise", "muscle_group": "Calves", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Barbell Standing Calf Raise", "muscle_group": "Calves", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Bodyweight Calf Raise", "muscle_group": "Calves", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Donkey Calf Raise", "muscle_group": "Calves", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Dumbbell Calf Raise", "muscle_group": "Calves", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Seated Calf Raise", "muscle_group": "Calves", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Single-Leg Calf Raise", "muscle_group": "Calves", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Standing Calf Raise", "muscle_group": "Calves", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Hack Squat Calf Raise", "muscle_group": "Calves", "equipment": "Machine", "pattern": "Isolation"},
    {"name": "Jump Rope", "muscle_group": "Calves", "equipment": "Bodyweight", "pattern": "Full Body"},
    {"name": "Leg Press Calf Raise", "muscle_group": "Calves", "equipment": "Machine", "pattern": "Isolation"},
    {"name": "Machine Seated Calf Raise", "muscle_group": "Calves", "equipment": "Machine", "pattern": "Isolation"},
    {"name": "Machine Standing Calf Raise", "muscle_group": "Calves", "equipment": "Machine", "pattern": "Isolation"},
    {"name": "Resistance Band Calf Raise", "muscle_group": "Calves", "equipment": "Resistance Band", "pattern": "Isolation"},
    {"name": "Seated Calf Raise", "muscle_group": "Calves", "equipment": "Machine", "pattern": "Isolation"},
    {"name": "Single Leg Calf Raise", "muscle_group": "Calves", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Single-Leg Bodyweight Calf Raise", "muscle_group": "Calves", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Smith Machine Calf Raise", "muscle_group": "Calves", "equipment": "Smith Machine", "pattern": "Isolation"},
    {"name": "Standing Calf Raise", "muscle_group": "Calves", "equipment": "Barbell", "pattern": "Isolation"},
    # === CHEST ===
    {"name": "Band Resisted Bench Press", "muscle_group": "Chest", "equipment": "Resistance Band", "pattern": "Push"},
    {"name": "Barbell Bench Press", "muscle_group": "Chest", "equipment": "Barbell", "pattern": "Push"},
    {"name": "Barbell Decline Bench Press", "muscle_group": "Chest", "equipment": "Barbell", "pattern": "Push"},
    {"name": "Barbell Floor Press", "muscle_group": "Chest", "equipment": "Barbell", "pattern": "Push"},
    {"name": "Barbell Incline Bench Press", "muscle_group": "Chest", "equipment": "Barbell", "pattern": "Push"},
    {"name": "Barbell Pullover", "muscle_group": "Chest", "equipment": "Barbell", "pattern": "Pull"},
    {"name": "Barbell Reverse Grip Bench Press", "muscle_group": "Chest", "equipment": "Barbell", "pattern": "Push"},
    {"name": "Board Press", "muscle_group": "Chest", "equipment": "Barbell", "pattern": "Push"},
    {"name": "Cable Chest Fly", "muscle_group": "Chest", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Chest Press", "muscle_group": "Chest", "equipment": "Cable", "pattern": "Push"},
    {"name": "Cable Crossover", "muscle_group": "Chest", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Fly", "muscle_group": "Chest", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable High-to-Low Chest Fly", "muscle_group": "Chest", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Incline Chest Press", "muscle_group": "Chest", "equipment": "Cable", "pattern": "Push"},
    {"name": "Cable Low Chest Fly", "muscle_group": "Chest", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Chain Bench Press", "muscle_group": "Chest", "equipment": "Barbell", "pattern": "Push"},
    {"name": "Chest Dip", "muscle_group": "Chest", "equipment": "Bodyweight", "pattern": "Push"},
    {"name": "Close Grip Bench Press", "muscle_group": "Chest", "equipment": "Barbell", "pattern": "Push"},
    {"name": "Close-Grip Bench Press", "muscle_group": "Chest", "equipment": "Barbell", "pattern": "Push"},
    {"name": "Decline Barbell Bench Press", "muscle_group": "Chest", "equipment": "Barbell", "pattern": "Push"},
    {"name": "Decline Dumbbell Bench Press", "muscle_group": "Chest", "equipment": "Dumbbell", "pattern": "Push"},
    {"name": "Decline Push Up", "muscle_group": "Chest", "equipment": "Bodyweight", "pattern": "Push"},
    {"name": "Decline Push-Up", "muscle_group": "Chest", "equipment": "Bodyweight", "pattern": "Push"},
    {"name": "Diamond Push Up", "muscle_group": "Chest", "equipment": "Bodyweight", "pattern": "Push"},
    {"name": "Dip (Chest Focus)", "muscle_group": "Chest", "equipment": "Bodyweight", "pattern": "Push"},
    {"name": "Dumbbell Bench Press", "muscle_group": "Chest", "equipment": "Dumbbell", "pattern": "Push"},
    {"name": "Dumbbell Chest Fly", "muscle_group": "Chest", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Decline Fly", "muscle_group": "Chest", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Decline Press", "muscle_group": "Chest", "equipment": "Dumbbell", "pattern": "Push"},
    {"name": "Dumbbell Floor Press", "muscle_group": "Chest", "equipment": "Dumbbell", "pattern": "Push"},
    {"name": "Dumbbell Fly", "muscle_group": "Chest", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Incline Fly", "muscle_group": "Chest", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Incline Press", "muscle_group": "Chest", "equipment": "Dumbbell", "pattern": "Push"},
    {"name": "Feet-Up Bench Press", "muscle_group": "Chest", "equipment": "Barbell", "pattern": "Push"},
    {"name": "Floor Press", "muscle_group": "Chest", "equipment": "Barbell", "pattern": "Push"},
    {"name": "High Cable Fly", "muscle_group": "Chest", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Incline Barbell Bench Press", "muscle_group": "Chest", "equipment": "Barbell", "pattern": "Push"},
    {"name": "Incline Dumbbell Bench Press", "muscle_group": "Chest", "equipment": "Dumbbell", "pattern": "Push"},
    {"name": "Incline Dumbbell Fly", "muscle_group": "Chest", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Incline Push Up", "muscle_group": "Chest", "equipment": "Bodyweight", "pattern": "Push"},
    {"name": "Landmine Chest Press", "muscle_group": "Chest", "equipment": "Landmine", "pattern": "Push"},
    {"name": "Landmine Press", "muscle_group": "Chest", "equipment": "Landmine", "pattern": "Push"},
    {"name": "Low Cable Fly", "muscle_group": "Chest", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Machine Chest Fly", "muscle_group": "Chest", "equipment": "Machine", "pattern": "Isolation"},
    {"name": "Machine Chest Press", "muscle_group": "Chest", "equipment": "Machine", "pattern": "Push"},
    {"name": "Pin Bench Press", "muscle_group": "Chest", "equipment": "Barbell", "pattern": "Push"},
    {"name": "Push Up", "muscle_group": "Chest", "equipment": "Bodyweight", "pattern": "Push"},
    {"name": "Push-Up", "muscle_group": "Chest", "equipment": "Bodyweight", "pattern": "Push"},
    {"name": "Resistance Band Chest Fly", "muscle_group": "Chest", "equipment": "Resistance Band", "pattern": "Isolation"},
    {"name": "Smith Machine Bench Press", "muscle_group": "Chest", "equipment": "Smith Machine", "pattern": "Push"},
    {"name": "Smith Machine Incline Bench Press", "muscle_group": "Chest", "equipment": "Smith Machine", "pattern": "Push"},
    {"name": "Svend Press", "muscle_group": "Chest", "equipment": "Dumbbell", "pattern": "Isolation"},
    # === FOREARMS ===
    {"name": "Barbell Reverse Wrist Curl", "muscle_group": "Forearms", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Barbell Wrist Curl", "muscle_group": "Forearms", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Behind Back Wrist Curl", "muscle_group": "Forearms", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Behind-the-Back Barbell Wrist Curl", "muscle_group": "Forearms", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Cable Reverse Wrist Curl", "muscle_group": "Forearms", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Wrist Curl", "muscle_group": "Forearms", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Dead Hang", "muscle_group": "Forearms", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Dumbbell Reverse Wrist Curl", "muscle_group": "Forearms", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Wrist Curl", "muscle_group": "Forearms", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Farmers Walk (Dumbbell)", "muscle_group": "Forearms", "equipment": "Dumbbell", "pattern": "Carry"},
    {"name": "Plate Pinch", "muscle_group": "Forearms", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Plate Pinch Hold", "muscle_group": "Forearms", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Towel Pull-Up (Grip)", "muscle_group": "Forearms", "equipment": "Bodyweight", "pattern": "Pull"},
    # === FULL BODY ===
    {"name": "Band Deadlift", "muscle_group": "Full Body", "equipment": "Resistance Band", "pattern": "Hinge"},
    {"name": "Barbell Clean and Jerk", "muscle_group": "Full Body", "equipment": "Barbell", "pattern": "Pull"},
    {"name": "Barbell Clean and Press", "muscle_group": "Full Body", "equipment": "Barbell", "pattern": "Pull"},
    {"name": "Barbell Deadlift", "muscle_group": "Full Body", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Barbell Deficit Deadlift", "muscle_group": "Full Body", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Barbell Hang Clean", "muscle_group": "Full Body", "equipment": "Barbell", "pattern": "Pull"},
    {"name": "Barbell Pause Deadlift", "muscle_group": "Full Body", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Barbell Power Clean", "muscle_group": "Full Body", "equipment": "Barbell", "pattern": "Pull"},
    {"name": "Barbell Rack Pull", "muscle_group": "Full Body", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Barbell Snatch", "muscle_group": "Full Body", "equipment": "Barbell", "pattern": "Pull"},
    {"name": "Barbell Sumo Deadlift (Full Body)", "muscle_group": "Full Body", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Barbell Thruster", "muscle_group": "Full Body", "equipment": "Barbell", "pattern": "Push"},
    {"name": "Battle Ropes", "muscle_group": "Full Body", "equipment": "Bodyweight", "pattern": "Full Body"},
    {"name": "Block Pull", "muscle_group": "Full Body", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Burpee", "muscle_group": "Full Body", "equipment": "Bodyweight", "pattern": "Full Body"},
    {"name": "Chain Deadlift", "muscle_group": "Full Body", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Clean", "muscle_group": "Full Body", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Clean and Press", "muscle_group": "Full Body", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Deficit Deadlift", "muscle_group": "Full Body", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Dumbbell Snatch", "muscle_group": "Full Body", "equipment": "Dumbbell", "pattern": "Hinge"},
    {"name": "Dumbbell Thruster", "muscle_group": "Full Body", "equipment": "Dumbbell", "pattern": "Squat"},
    {"name": "Elliptical", "muscle_group": "Full Body", "equipment": "Machine", "pattern": "Full Body"},
    {"name": "Hang Clean", "muscle_group": "Full Body", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Heavy Bag Work", "muscle_group": "Full Body", "equipment": "Bodyweight", "pattern": "Full Body"},
    {"name": "Kettlebell Turkish Get-Up", "muscle_group": "Full Body", "equipment": "Kettlebell", "pattern": "Carry"},
    {"name": "Man Maker", "muscle_group": "Full Body", "equipment": "Dumbbell", "pattern": "Full Body"},
    {"name": "Pause Deadlift", "muscle_group": "Full Body", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Power Clean", "muscle_group": "Full Body", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Shadow Boxing", "muscle_group": "Full Body", "equipment": "Bodyweight", "pattern": "Full Body"},
    {"name": "Snatch", "muscle_group": "Full Body", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Thruster", "muscle_group": "Full Body", "equipment": "Barbell", "pattern": "Squat"},
    {"name": "Trap Bar Deadlift", "muscle_group": "Full Body", "equipment": "Trap Bar", "pattern": "Hinge"},
    {"name": "Trap Bar Farmers Walk", "muscle_group": "Full Body", "equipment": "Trap Bar", "pattern": "Carry"},
    {"name": "Trap Bar Figure-8 Carry", "muscle_group": "Full Body", "equipment": "Trap Bar", "pattern": "Carry"},
    {"name": "Trap Bar Floor Press", "muscle_group": "Full Body", "equipment": "Trap Bar", "pattern": "Push"},
    {"name": "Trap Bar Jump Squat", "muscle_group": "Full Body", "equipment": "Trap Bar", "pattern": "Squat"},
    {"name": "Trap Bar Rack Pull", "muscle_group": "Full Body", "equipment": "Trap Bar", "pattern": "Hinge"},
    {"name": "Trap Bar Suitcase Carry", "muscle_group": "Full Body", "equipment": "Trap Bar", "pattern": "Carry"},
    {"name": "Treadmill Run", "muscle_group": "Full Body", "equipment": "Machine", "pattern": "Full Body"},
    {"name": "Treadmill Sprint", "muscle_group": "Full Body", "equipment": "Machine", "pattern": "Full Body"},
    {"name": "Treadmill Walk (Incline)", "muscle_group": "Full Body", "equipment": "Machine", "pattern": "Full Body"},
    {"name": "Turkish Get Up", "muscle_group": "Full Body", "equipment": "Dumbbell", "pattern": "Full Body"},
    # === GLUTES ===
    {"name": "Band Clamshell", "muscle_group": "Glutes", "equipment": "Resistance Band", "pattern": "Isolation"},
    {"name": "Band Hip Thrust", "muscle_group": "Glutes", "equipment": "Resistance Band", "pattern": "Hinge"},
    {"name": "Band Lateral Walk", "muscle_group": "Glutes", "equipment": "Resistance Band", "pattern": "Isolation"},
    {"name": "Barbell Glute Bridge", "muscle_group": "Glutes", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Barbell High-Bar Squat (Glutes)", "muscle_group": "Glutes", "equipment": "Barbell", "pattern": "Squat"},
    {"name": "Barbell Hip Thrust", "muscle_group": "Glutes", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Barbell Sumo Deadlift", "muscle_group": "Glutes", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Cable Glute Kickback", "muscle_group": "Glutes", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Hip Abduction", "muscle_group": "Glutes", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Hip Extension (Kickback)", "muscle_group": "Glutes", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Pull-Through (Glutes)", "muscle_group": "Glutes", "equipment": "Cable", "pattern": "Hinge"},
    {"name": "Curtsy Lunge", "muscle_group": "Glutes", "equipment": "Bodyweight", "pattern": "Lunge"},
    {"name": "Dumbbell Deadlift", "muscle_group": "Glutes", "equipment": "Dumbbell", "pattern": "Hinge"},
    {"name": "Dumbbell Glute Bridge", "muscle_group": "Glutes", "equipment": "Dumbbell", "pattern": "Hinge"},
    {"name": "Dumbbell Hip Thrust", "muscle_group": "Glutes", "equipment": "Dumbbell", "pattern": "Hinge"},
    {"name": "Dumbbell Sumo Squat", "muscle_group": "Glutes", "equipment": "Dumbbell", "pattern": "Squat"},
    {"name": "Frog Pump", "muscle_group": "Glutes", "equipment": "Bodyweight", "pattern": "Hinge"},
    {"name": "Glute Bridge", "muscle_group": "Glutes", "equipment": "Bodyweight", "pattern": "Hinge"},
    {"name": "Glute Bridge (Bodyweight)", "muscle_group": "Glutes", "equipment": "Bodyweight", "pattern": "Hinge"},
    {"name": "Hip Adduction Machine", "muscle_group": "Glutes", "equipment": "Machine", "pattern": "Isolation"},
    {"name": "Kettlebell Goblet Squat", "muscle_group": "Glutes", "equipment": "Kettlebell", "pattern": "Squat"},
    {"name": "Kettlebell Sumo Deadlift", "muscle_group": "Glutes", "equipment": "Kettlebell", "pattern": "Hinge"},
    {"name": "Landmine Reverse Lunge", "muscle_group": "Glutes", "equipment": "Landmine", "pattern": "Lunge"},
    {"name": "Machine Hip Thrust", "muscle_group": "Glutes", "equipment": "Machine", "pattern": "Hinge"},
    {"name": "Resistance Band Clamshell", "muscle_group": "Glutes", "equipment": "Resistance Band", "pattern": "Isolation"},
    {"name": "Resistance Band Hip Thrust", "muscle_group": "Glutes", "equipment": "Resistance Band", "pattern": "Hinge"},
    {"name": "Single Leg Hip Thrust", "muscle_group": "Glutes", "equipment": "Bodyweight", "pattern": "Hinge"},
    {"name": "Single-Leg Glute Bridge", "muscle_group": "Glutes", "equipment": "Bodyweight", "pattern": "Hinge"},
    {"name": "Sled Leg Press (Wide Stance)", "muscle_group": "Glutes", "equipment": "Machine", "pattern": "Squat"},
    {"name": "Sumo Deadlift", "muscle_group": "Glutes", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Wide Stance Leg Press", "muscle_group": "Glutes", "equipment": "Machine", "pattern": "Squat"},
    # === HAMSTRINGS ===
    {"name": "Band Good Morning", "muscle_group": "Hamstrings", "equipment": "Resistance Band", "pattern": "Hinge"},
    {"name": "Barbell Good Morning (Hamstrings)", "muscle_group": "Hamstrings", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Barbell Romanian Deadlift", "muscle_group": "Hamstrings", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Barbell Stiff-Leg Deadlift", "muscle_group": "Hamstrings", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Cable Leg Curl", "muscle_group": "Hamstrings", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Pull Through", "muscle_group": "Hamstrings", "equipment": "Cable", "pattern": "Hinge"},
    {"name": "Cable Pull-Through", "muscle_group": "Hamstrings", "equipment": "Cable", "pattern": "Hinge"},
    {"name": "Dumbbell Romanian Deadlift", "muscle_group": "Hamstrings", "equipment": "Dumbbell", "pattern": "Hinge"},
    {"name": "Dumbbell Single-Leg Romanian Deadlift", "muscle_group": "Hamstrings", "equipment": "Dumbbell", "pattern": "Hinge"},
    {"name": "Dumbbell Stiff-Leg Deadlift", "muscle_group": "Hamstrings", "equipment": "Dumbbell", "pattern": "Hinge"},
    {"name": "Glute Ham Raise", "muscle_group": "Hamstrings", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Glute-Ham Raise", "muscle_group": "Hamstrings", "equipment": "Bodyweight", "pattern": "Hinge"},
    {"name": "Good Morning", "muscle_group": "Hamstrings", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Kettlebell Swing", "muscle_group": "Hamstrings", "equipment": "Kettlebell", "pattern": "Hinge"},
    {"name": "Leg Curl", "muscle_group": "Hamstrings", "equipment": "Machine", "pattern": "Isolation"},
    {"name": "Lying Leg Curl", "muscle_group": "Hamstrings", "equipment": "Machine", "pattern": "Isolation"},
    {"name": "Nordic Hamstring Curl", "muscle_group": "Hamstrings", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Resistance Band Good Morning", "muscle_group": "Hamstrings", "equipment": "Resistance Band", "pattern": "Hinge"},
    {"name": "Resistance Band Leg Curl", "muscle_group": "Hamstrings", "equipment": "Resistance Band", "pattern": "Isolation"},
    {"name": "Seated Good Morning", "muscle_group": "Hamstrings", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Seated Leg Curl", "muscle_group": "Hamstrings", "equipment": "Machine", "pattern": "Isolation"},
    {"name": "Single Leg Curl", "muscle_group": "Hamstrings", "equipment": "Machine", "pattern": "Isolation"},
    {"name": "Single Leg Romanian Deadlift", "muscle_group": "Hamstrings", "equipment": "Dumbbell", "pattern": "Hinge"},
    {"name": "Single-Leg Lying Leg Curl", "muscle_group": "Hamstrings", "equipment": "Machine", "pattern": "Isolation"},
    {"name": "Single-Leg Seated Leg Curl", "muscle_group": "Hamstrings", "equipment": "Machine", "pattern": "Isolation"},
    {"name": "Smith Machine Romanian Deadlift", "muscle_group": "Hamstrings", "equipment": "Smith Machine", "pattern": "Hinge"},
    {"name": "Standing Leg Curl", "muscle_group": "Hamstrings", "equipment": "Machine", "pattern": "Isolation"},
    {"name": "Stiff Leg Deadlift", "muscle_group": "Hamstrings", "equipment": "Barbell", "pattern": "Hinge"},
    {"name": "Trap Bar Romanian Deadlift", "muscle_group": "Hamstrings", "equipment": "Trap Bar", "pattern": "Hinge"},
    # === LATS ===
    {"name": "Archer Pull-Up", "muscle_group": "Lats", "equipment": "Bodyweight", "pattern": "Pull"},
    {"name": "Barbell Pullover (Lats)", "muscle_group": "Lats", "equipment": "Barbell", "pattern": "Pull"},
    {"name": "Cable Rope Pulldown", "muscle_group": "Lats", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Chin-Up", "muscle_group": "Lats", "equipment": "Bodyweight", "pattern": "Pull"},
    {"name": "Close-Grip Chin-Up", "muscle_group": "Lats", "equipment": "Bodyweight", "pattern": "Pull"},
    {"name": "Close-Grip Lat Pulldown", "muscle_group": "Lats", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Dumbbell Pullover (Lats)", "muscle_group": "Lats", "equipment": "Dumbbell", "pattern": "Pull"},
    {"name": "Lat Pulldown (Neutral Grip)", "muscle_group": "Lats", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Lat Pulldown (Supinated Grip)", "muscle_group": "Lats", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Lat Pulldown (Wide Grip)", "muscle_group": "Lats", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Muscle-Up", "muscle_group": "Lats", "equipment": "Bodyweight", "pattern": "Pull"},
    {"name": "Neutral-Grip Pull-Up", "muscle_group": "Lats", "equipment": "Bodyweight", "pattern": "Pull"},
    {"name": "One-Arm Lat Pulldown", "muscle_group": "Lats", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Pull-Up", "muscle_group": "Lats", "equipment": "Bodyweight", "pattern": "Pull"},
    {"name": "Resistance Band Lat Pulldown", "muscle_group": "Lats", "equipment": "Resistance Band", "pattern": "Pull"},
    {"name": "Resistance Band Pull-Up (Assisted)", "muscle_group": "Lats", "equipment": "Resistance Band", "pattern": "Pull"},
    {"name": "Weighted Chin-Up", "muscle_group": "Lats", "equipment": "Bodyweight", "pattern": "Pull"},
    {"name": "Weighted Pull-Up", "muscle_group": "Lats", "equipment": "Bodyweight", "pattern": "Pull"},
    {"name": "Wide-Grip Pull-Up", "muscle_group": "Lats", "equipment": "Bodyweight", "pattern": "Pull"},
    # === OBLIQUES ===
    {"name": "Bicycle Crunch", "muscle_group": "Obliques", "equipment": "Bodyweight", "pattern": "Rotation"},
    {"name": "Cable Side Bend", "muscle_group": "Obliques", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Woodchop (High-to-Low)", "muscle_group": "Obliques", "equipment": "Cable", "pattern": "Rotation"},
    {"name": "Cable Woodchop (Low-to-High)", "muscle_group": "Obliques", "equipment": "Cable", "pattern": "Rotation"},
    {"name": "Copenhagen Plank", "muscle_group": "Obliques", "equipment": "Bodyweight", "pattern": "Isolation"},
    {"name": "Dumbbell Side Bend", "muscle_group": "Obliques", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Kettlebell Windmill", "muscle_group": "Obliques", "equipment": "Kettlebell", "pattern": "Rotation"},
    {"name": "Landmine Anti-Rotation", "muscle_group": "Obliques", "equipment": "Landmine", "pattern": "Rotation"},
    {"name": "Resistance Band Woodchop", "muscle_group": "Obliques", "equipment": "Resistance Band", "pattern": "Rotation"},
    {"name": "Russian Twist (Weighted)", "muscle_group": "Obliques", "equipment": "Dumbbell", "pattern": "Rotation"},
    {"name": "Suitcase Carry (Dumbbell)", "muscle_group": "Obliques", "equipment": "Dumbbell", "pattern": "Carry"},
    # === QUADS ===
    {"name": "Band Squat", "muscle_group": "Quads", "equipment": "Resistance Band", "pattern": "Squat"},
    {"name": "Barbell Back Squat", "muscle_group": "Quads", "equipment": "Barbell", "pattern": "Squat"},
    {"name": "Barbell Box Squat", "muscle_group": "Quads", "equipment": "Barbell", "pattern": "Squat"},
    {"name": "Barbell Bulgarian Split Squat", "muscle_group": "Quads", "equipment": "Barbell", "pattern": "Lunge"},
    {"name": "Barbell Front Squat", "muscle_group": "Quads", "equipment": "Barbell", "pattern": "Squat"},
    {"name": "Barbell Hack Squat", "muscle_group": "Quads", "equipment": "Barbell", "pattern": "Squat"},
    {"name": "Barbell Lunge", "muscle_group": "Quads", "equipment": "Barbell", "pattern": "Lunge"},
    {"name": "Barbell Overhead Squat", "muscle_group": "Quads", "equipment": "Barbell", "pattern": "Squat"},
    {"name": "Barbell Pause Squat", "muscle_group": "Quads", "equipment": "Barbell", "pattern": "Squat"},
    {"name": "Barbell Pin Squat", "muscle_group": "Quads", "equipment": "Barbell", "pattern": "Squat"},
    {"name": "Barbell Reverse Lunge", "muscle_group": "Quads", "equipment": "Barbell", "pattern": "Lunge"},
    {"name": "Barbell Squat", "muscle_group": "Quads", "equipment": "Barbell", "pattern": "Squat"},
    {"name": "Barbell Walking Lunge", "muscle_group": "Quads", "equipment": "Barbell", "pattern": "Lunge"},
    {"name": "Barbell Zercher Squat", "muscle_group": "Quads", "equipment": "Barbell", "pattern": "Squat"},
    {"name": "Bodyweight Squat", "muscle_group": "Quads", "equipment": "Bodyweight", "pattern": "Squat"},
    {"name": "Box Squat", "muscle_group": "Quads", "equipment": "Barbell", "pattern": "Squat"},
    {"name": "Bulgarian Split Squat", "muscle_group": "Quads", "equipment": "Dumbbell", "pattern": "Lunge"},
    {"name": "Chain Squat", "muscle_group": "Quads", "equipment": "Barbell", "pattern": "Squat"},
    {"name": "Dumbbell Bulgarian Split Squat", "muscle_group": "Quads", "equipment": "Dumbbell", "pattern": "Lunge"},
    {"name": "Dumbbell Lunge", "muscle_group": "Quads", "equipment": "Dumbbell", "pattern": "Lunge"},
    {"name": "Dumbbell Reverse Lunge", "muscle_group": "Quads", "equipment": "Dumbbell", "pattern": "Lunge"},
    {"name": "Dumbbell Squat", "muscle_group": "Quads", "equipment": "Dumbbell", "pattern": "Squat"},
    {"name": "Dumbbell Step-Up", "muscle_group": "Quads", "equipment": "Dumbbell", "pattern": "Lunge"},
    {"name": "Dumbbell Walking Lunge", "muscle_group": "Quads", "equipment": "Dumbbell", "pattern": "Lunge"},
    {"name": "Front Squat", "muscle_group": "Quads", "equipment": "Barbell", "pattern": "Squat"},
    {"name": "Goblet Squat", "muscle_group": "Quads", "equipment": "Dumbbell", "pattern": "Squat"},
    {"name": "Hack Squat", "muscle_group": "Quads", "equipment": "Machine", "pattern": "Squat"},
    {"name": "Hack Squat Machine", "muscle_group": "Quads", "equipment": "Machine", "pattern": "Squat"},
    {"name": "Jump Squat", "muscle_group": "Quads", "equipment": "Bodyweight", "pattern": "Squat"},
    {"name": "Kettlebell Front Squat", "muscle_group": "Quads", "equipment": "Kettlebell", "pattern": "Squat"},
    {"name": "Landmine Hack Squat", "muscle_group": "Quads", "equipment": "Landmine", "pattern": "Squat"},
    {"name": "Landmine Squat", "muscle_group": "Quads", "equipment": "Landmine", "pattern": "Squat"},
    {"name": "Leg Extension", "muscle_group": "Quads", "equipment": "Machine", "pattern": "Isolation"},
    {"name": "Leg Press", "muscle_group": "Quads", "equipment": "Machine", "pattern": "Squat"},
    {"name": "Narrow Stance Leg Press", "muscle_group": "Quads", "equipment": "Machine", "pattern": "Squat"},
    {"name": "Pause Squat", "muscle_group": "Quads", "equipment": "Barbell", "pattern": "Squat"},
    {"name": "Pistol Squat", "muscle_group": "Quads", "equipment": "Bodyweight", "pattern": "Squat"},
    {"name": "Reverse Lunge", "muscle_group": "Quads", "equipment": "Dumbbell", "pattern": "Lunge"},
    {"name": "Safety Bar Squat", "muscle_group": "Quads", "equipment": "Barbell", "pattern": "Squat"},
    {"name": "Single Leg Extension", "muscle_group": "Quads", "equipment": "Machine", "pattern": "Isolation"},
    {"name": "Single Leg Press", "muscle_group": "Quads", "equipment": "Machine", "pattern": "Squat"},
    {"name": "Single-Leg Leg Extension", "muscle_group": "Quads", "equipment": "Machine", "pattern": "Isolation"},
    {"name": "Sissy Squat", "muscle_group": "Quads", "equipment": "Bodyweight", "pattern": "Squat"},
    {"name": "Smith Machine Front Squat", "muscle_group": "Quads", "equipment": "Smith Machine", "pattern": "Squat"},
    {"name": "Smith Machine Squat", "muscle_group": "Quads", "equipment": "Smith Machine", "pattern": "Squat"},
    {"name": "Step Up", "muscle_group": "Quads", "equipment": "Dumbbell", "pattern": "Lunge"},
    {"name": "Walking Lunge", "muscle_group": "Quads", "equipment": "Dumbbell", "pattern": "Lunge"},
    {"name": "Zercher Squat", "muscle_group": "Quads", "equipment": "Barbell", "pattern": "Squat"},
    # === SHOULDERS ===
    {"name": "Arnold Press", "muscle_group": "Shoulders", "equipment": "Dumbbell", "pattern": "Push"},
    {"name": "Band Lateral Raise", "muscle_group": "Shoulders", "equipment": "Resistance Band", "pattern": "Isolation"},
    {"name": "Band Pull Apart (Shoulders)", "muscle_group": "Shoulders", "equipment": "Resistance Band", "pattern": "Pull"},
    {"name": "Barbell Front Raise", "muscle_group": "Shoulders", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Barbell Overhead Press", "muscle_group": "Shoulders", "equipment": "Barbell", "pattern": "Push"},
    {"name": "Barbell Push Press", "muscle_group": "Shoulders", "equipment": "Barbell", "pattern": "Push"},
    {"name": "Barbell Rear Delt Row", "muscle_group": "Shoulders", "equipment": "Barbell", "pattern": "Pull"},
    {"name": "Barbell Upright Row", "muscle_group": "Shoulders", "equipment": "Barbell", "pattern": "Pull"},
    {"name": "Barbell Z Press", "muscle_group": "Shoulders", "equipment": "Barbell", "pattern": "Push"},
    {"name": "Behind the Neck Press", "muscle_group": "Shoulders", "equipment": "Barbell", "pattern": "Push"},
    {"name": "Behind-the-Neck Press", "muscle_group": "Shoulders", "equipment": "Barbell", "pattern": "Push"},
    {"name": "Cable External Rotation", "muscle_group": "Shoulders", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Face Pull", "muscle_group": "Shoulders", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Cable Front Raise", "muscle_group": "Shoulders", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Internal Rotation", "muscle_group": "Shoulders", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Lateral Raise", "muscle_group": "Shoulders", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Reverse Fly", "muscle_group": "Shoulders", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Upright Row", "muscle_group": "Shoulders", "equipment": "Cable", "pattern": "Pull"},
    {"name": "Dumbbell Front Raise", "muscle_group": "Shoulders", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Lateral Raise", "muscle_group": "Shoulders", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Rear Delt Row", "muscle_group": "Shoulders", "equipment": "Dumbbell", "pattern": "Pull"},
    {"name": "Dumbbell Reverse Fly", "muscle_group": "Shoulders", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Reverse Fly (Incline)", "muscle_group": "Shoulders", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Shoulder Press", "muscle_group": "Shoulders", "equipment": "Dumbbell", "pattern": "Push"},
    {"name": "Dumbbell Upright Row", "muscle_group": "Shoulders", "equipment": "Dumbbell", "pattern": "Pull"},
    {"name": "Incline Lateral Raise", "muscle_group": "Shoulders", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Kettlebell Halo", "muscle_group": "Shoulders", "equipment": "Kettlebell", "pattern": "Rotation"},
    {"name": "Kettlebell Press", "muscle_group": "Shoulders", "equipment": "Kettlebell", "pattern": "Push"},
    {"name": "Kettlebell Push Press", "muscle_group": "Shoulders", "equipment": "Kettlebell", "pattern": "Push"},
    {"name": "Landmine Lateral Raise", "muscle_group": "Shoulders", "equipment": "Landmine", "pattern": "Isolation"},
    {"name": "Landmine One-Arm Press", "muscle_group": "Shoulders", "equipment": "Landmine", "pattern": "Push"},
    {"name": "Landmine Shoulder Press", "muscle_group": "Shoulders", "equipment": "Landmine", "pattern": "Push"},
    {"name": "Lu Raise", "muscle_group": "Shoulders", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Machine Lateral Raise", "muscle_group": "Shoulders", "equipment": "Machine", "pattern": "Isolation"},
    {"name": "Machine Reverse Fly", "muscle_group": "Shoulders", "equipment": "Machine", "pattern": "Isolation"},
    {"name": "Machine Shoulder Press", "muscle_group": "Shoulders", "equipment": "Machine", "pattern": "Push"},
    {"name": "Plate Front Raise", "muscle_group": "Shoulders", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Push Press", "muscle_group": "Shoulders", "equipment": "Barbell", "pattern": "Push"},
    {"name": "Resistance Band Lateral Raise", "muscle_group": "Shoulders", "equipment": "Resistance Band", "pattern": "Isolation"},
    {"name": "Resistance Band Shoulder Press", "muscle_group": "Shoulders", "equipment": "Resistance Band", "pattern": "Push"},
    {"name": "Seated Barbell Overhead Press", "muscle_group": "Shoulders", "equipment": "Barbell", "pattern": "Push"},
    {"name": "Seated Dumbbell Shoulder Press", "muscle_group": "Shoulders", "equipment": "Dumbbell", "pattern": "Push"},
    {"name": "Speed Bag Work", "muscle_group": "Shoulders", "equipment": "Bodyweight", "pattern": "Full Body"},
    {"name": "Z Press", "muscle_group": "Shoulders", "equipment": "Barbell", "pattern": "Push"},
    # === TRAPS ===
    {"name": "Band Pull-Apart", "muscle_group": "Traps", "equipment": "Resistance Band", "pattern": "Pull"},
    {"name": "Barbell Behind Back Shrug", "muscle_group": "Traps", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Barbell Behind-the-Back Shrug", "muscle_group": "Traps", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Barbell High Pull", "muscle_group": "Traps", "equipment": "Barbell", "pattern": "Pull"},
    {"name": "Barbell Shrug", "muscle_group": "Traps", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Cable Shrug", "muscle_group": "Traps", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Dumbbell Incline Shrug", "muscle_group": "Traps", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Shrug", "muscle_group": "Traps", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Y-Raise (Incline)", "muscle_group": "Traps", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Farmers Walk", "muscle_group": "Traps", "equipment": "Dumbbell", "pattern": "Carry"},
    {"name": "Kettlebell Sumo High Pull", "muscle_group": "Traps", "equipment": "Kettlebell", "pattern": "Pull"},
    {"name": "Kettlebell Upright Row", "muscle_group": "Traps", "equipment": "Kettlebell", "pattern": "Pull"},
    {"name": "Scapular Pull-Up", "muscle_group": "Traps", "equipment": "Bodyweight", "pattern": "Pull"},
    {"name": "Smith Machine Shrug", "muscle_group": "Traps", "equipment": "Smith Machine", "pattern": "Isolation"},
    {"name": "Trap Bar Carry", "muscle_group": "Traps", "equipment": "Trap Bar", "pattern": "Carry"},
    {"name": "Trap Bar Shrug", "muscle_group": "Traps", "equipment": "Trap Bar", "pattern": "Isolation"},
    # === TRICEPS ===
    {"name": "Band Tricep Pushdown", "muscle_group": "Triceps", "equipment": "Resistance Band", "pattern": "Isolation"},
    {"name": "Barbell Incline Triceps Extension", "muscle_group": "Triceps", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Barbell Lying Triceps Extension (Skull Crusher)", "muscle_group": "Triceps", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Barbell Standing Triceps Extension", "muscle_group": "Triceps", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Bench Dip", "muscle_group": "Triceps", "equipment": "Bodyweight", "pattern": "Push"},
    {"name": "Cable Crossbody Triceps Extension", "muscle_group": "Triceps", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Kickback", "muscle_group": "Triceps", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable One-Arm Tricep Pushdown", "muscle_group": "Triceps", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Overhead Tricep Extension", "muscle_group": "Triceps", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Overhead Triceps Extension", "muscle_group": "Triceps", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Tricep Pushdown", "muscle_group": "Triceps", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Tricep Pushdown (Bar)", "muscle_group": "Triceps", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Tricep Pushdown (Rope)", "muscle_group": "Triceps", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Cable Tricep Pushdown (V-Bar)", "muscle_group": "Triceps", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Close-Grip Push-Up", "muscle_group": "Triceps", "equipment": "Bodyweight", "pattern": "Push"},
    {"name": "Diamond Push Up (Triceps)", "muscle_group": "Triceps", "equipment": "Bodyweight", "pattern": "Push"},
    {"name": "Diamond Push-Up", "muscle_group": "Triceps", "equipment": "Bodyweight", "pattern": "Push"},
    {"name": "Dip (Tricep Focus)", "muscle_group": "Triceps", "equipment": "Bodyweight", "pattern": "Push"},
    {"name": "Dumbbell Close-Grip Press", "muscle_group": "Triceps", "equipment": "Dumbbell", "pattern": "Push"},
    {"name": "Dumbbell Kickback", "muscle_group": "Triceps", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Lying Triceps Extension", "muscle_group": "Triceps", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Overhead Tricep Extension", "muscle_group": "Triceps", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Overhead Triceps Extension", "muscle_group": "Triceps", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Skull Crusher", "muscle_group": "Triceps", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Dumbbell Tate Press", "muscle_group": "Triceps", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "EZ Bar Close-Grip Bench Press", "muscle_group": "Triceps", "equipment": "EZ Bar", "pattern": "Push"},
    {"name": "EZ Bar Lying Triceps Extension", "muscle_group": "Triceps", "equipment": "EZ Bar", "pattern": "Isolation"},
    {"name": "EZ Bar Seated Triceps Extension", "muscle_group": "Triceps", "equipment": "EZ Bar", "pattern": "Isolation"},
    {"name": "JM Press", "muscle_group": "Triceps", "equipment": "Barbell", "pattern": "Push"},
    {"name": "Rope Pushdown", "muscle_group": "Triceps", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Single Arm Cable Pushdown", "muscle_group": "Triceps", "equipment": "Cable", "pattern": "Isolation"},
    {"name": "Skull Crusher", "muscle_group": "Triceps", "equipment": "Barbell", "pattern": "Isolation"},
    {"name": "Tate Press", "muscle_group": "Triceps", "equipment": "Dumbbell", "pattern": "Isolation"},
    {"name": "Tricep Dip", "muscle_group": "Triceps", "equipment": "Bodyweight", "pattern": "Push"},
]

def get_exercises():
    return EXERCISES

if __name__ == "__main__":
    print(f"Total exercises: {len(EXERCISES)}")
    groups = {}
    for ex in EXERCISES:
        g = ex["muscle_group"]
        groups[g] = groups.get(g, 0) + 1
    for g, count in sorted(groups.items(), key=lambda x: -x[1]):
        print(f"  {g}: {count}")
